In [ ]:
import numpy as np

In [ ]:
class Employee():
    # create data members to keep count of employee count and list of salaries
    emp_count = 0

    # constructor to initilize the variables
    def __init__(self,name,family,salary,department):
        self.name = name,
        self.family = family,
        self.salary = salary,
        self.department = department,
        Employee.emp_count += 1

    # funtion to return average of salary
    def avg_salary(employees:list):
        salaries_list = [emp.salary[0] for emp in employees]
        avg_sal = sum(salaries_list)/Employee.emp_count
        return avg_sal

# created FullTimeEmployee class and inherit the properties from Employee class
class FullTimeEmployee(Employee):
    def __init__(self,name,family,salary,department):
        # calling parent class constructor
        super().__init__(name,family,salary,department)

employees = []
employees.append(Employee("Naveen","Palem",50000,"analytics"))
employees.append(Employee("Vedamsh"," Reddy",75000,"CTO"))

employees.append(FullTimeEmployee(" Praneeth "," Chinnasama ",60000,"data science"))
employees.append(FullTimeEmployee(" Rupesh "," Gundeti",85000,"data analytics"))


print("using employee class",Employee.avg_salary(employees))
print("using fulltime employee class",FullTimeEmployee.avg_salary(employees))

using employee class 67500.0
using fulltime employee class 67500.0


In [ ]:
arr = np.random.uniform(1,20,20)
arr = arr.reshape(4,5)

In [16]:
# Task : replace the max in each row by 0 (axis = 1)

# print array before replacement
print("Array before :\n\n",arr,end="\n\n\n")

# get max elements of each row and reshape it
each_row_max = np.max(arr,axis = 1).reshape(-1,1)

arr[arr == each_row_max] = 0

# print array after replacement
print("Array after replace the max element of each row with 0: \n\n", arr)

Array before :

 [[0.         0.         0.         1.         1.26940775]
 [0.         0.         1.22001392 0.         1.        ]
 [1.         0.         0.         1.66623788 0.        ]
 [0.         0.         2.5242191  0.         1.        ]]


Array after replace the max element of each row with 0: 

 [[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


ICP2 NEURAL NETWORKS
DISHA REDDY- 700755814
https://drive.google.com/file/d/1DW0KZMkWpG6wuJvHt5JB8J1RkbJ0m322/view?usp=sharing